
// Objective-C API for talking to the following Go packages
//
//	github.com/zarz/spotiflac_android/go_backend
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gobackend_FRAMEWORK_H__
#define __Gobackend_FRAMEWORK_H__

#include "Gobackend.objc.h"
#include "Universe.objc.h"

#endif
